### ISSUE TITLE
Some typos in readme and in code.

### ISSUE THREAD

**Issue by ricardochen** [westracer/flutter_native_opencv#2]
First of all, thank you for your amazing tutorial.

There is a typo in the readme, specifically in:
Contents of OpenCV-android-sdk/sdk/native/jni/libs/** to native_opencv/android/src/main/jniLibs
should be 
OpenCV-android-sdk/sdk/native/libs/** instead of OpenCV-android-sdk/sdk/native/jni/libs/**   (there is an extra "jni" in the path)

In code of native_opencv.cpp:
you commented out the for-loop of "doing a lot of work" leaving out two required lines:
adaptiveThreshold(input, threshed, 255, ADAPTIVE_THRESH_GAUSSIAN_C, THRESH_BINARY_INV, 77, 6);
findContours(threshed, contours, hierarchy, RETR_TREE, CHAIN_APPROX_TC89_L1);

After fixing these minor issues, everything works phenomenally.

**Comment by westracer** [comment]
Hello. Thank you for your feedback.

You're right about native libs' location in OpenCV's SDK, but I'm not sure about "jni/libs" instead of "jniLibs", as I specified "jniLibs" folder in `set_target_properties` command's `IMPORTED_LOCATION` prop:

```cmake
set_target_properties(lib_opencv PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libopencv_java4.so)
```
