### ISSUE TITLE
windows/linux support

### ISSUE THREAD

**Issue by weypro** [westracer/flutter_native_opencv#7]
Hi. I want to know how to run the program on Windows or Linux.

**Comment by westracer** [comment]
Hello. Flutter desktop is still in beta, so I'm not sure if it's even possible to run and build this project properly. The build systems can change in the future as well.

I'll take a look at it later, though I'm unfamiliar with Linux apps' build system and have already forgotten what windows apps' build system looks like.

**Comment by westracer** [comment]
I have added Windows, macOS, and Linux plugins to the repo. Instructions on how to build the project for different platforms are available in the readme file. The second article is to be checked and published by Flutter Community's moderators.

If there are any problems feel free to create a new issue.
