### ISSUE TITLE
iOS Linking issue

### ISSUE THREAD

**Issue by sonnyiosa** [westracer/flutter_native_opencv#8]
Hi, 
I follow your instructions (run init.sh) . in Android it worked perfectly fine. but in iOS i'm having some issue.

"framework not found opencv2" when i run on ios (both simulator and real device).

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, version): symbol not found)

When the exception was thrown, this was the stack:
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)

```

What should I do ?

**Comment by westracer** [comment]
Hello. I have updated the project - everything should be working now on iOS. And it's better to run `flutter clean` or even re-clone the repo before building again.

Feel free to reopen the issue if there's still a problem
