### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

### ISSUE THREAD

**Issue by arsies** [westracer/flutter_native_opencv#9]
i was trying to run it in my android device and this error happened. 

Note: /Users/rndtss/FlutterDev/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.6/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':native_opencv:stripDebugDebugSymbols'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Exception: Gradle task assembleDebug failed with exit code 1

it works on my ios device. Is there any step that i missed for the android ?

**Comment by westracer** [comment]
Hello. What version of Android NDK do you have installed? Maybe try downgrading it to `20.1.xxxxx` version.

**Comment by arsies** [comment]
Thank you, im using `23.1.xxxx` version before. And after downgrading it to 20 version, it works. Thanks
